name: lint

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint
        run: ./scripts/format.sh

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          extra-args: 
            "reportMissingImports=false"
